kind: pipeline
name: default
steps:
- name: build
  image: node:12
  commands:
  - npm install
  - npm test
  - npm run build
- name: npm
  image: plugins/npm
  settings:
    token:
      from_secret: npm_token
  when:
    event: tag
